global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:8888']   # l’endpoint /metrics de l’all‑in‑one
  - job_name: 'webapi'
    static_configs:
      - targets: ['host.docker.internal:6001']
  - job_name: 'webapp'
    static_configs:
      - targets: ['host.docker.internal:7001']
  - job_name: 'management'
    static_configs:
      - targets: ['host.docker.internal:8001']
